name: E2E Deploy & Test (EC2)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ollama
      BROWSERS: "chrome firefox"
      RESOLUTIONS: "1920x1080 1366x768"

    steps:
      - name: Checkout OllamaUI
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Compute YOLO tag
        run: |
          if [ -n "${{ secrets.YOLO_IMAGE_TAG }}" ]; then
            echo "YOLO_TAG=${{ secrets.YOLO_IMAGE_TAG }}" >> $GITHUB_ENV
          else
            echo "YOLO_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build & push OllamaUI image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Copy docker-compose.yaml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/ubuntu/"

      - name: Deploy stack on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 45m   # <— longer so big pulls don’t kill the job
          script: |
            set -euo pipefail

            # Ensure Docker & compose plugin exist and Docker is running
            if ! docker compose version >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io docker-compose-plugin
              sudo systemctl enable --now docker
            fi

            cd /home/ubuntu

            # Login to Docker Hub on the instance
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # === Env vars EXACTLY as your docker-compose.yaml expects ===
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_NAMESPACE }}"
            export OLLAMA_UI_IMG_TAG="${{ env.IMAGE_TAG }}"
            export YOLO_IMG_TAG="${{ env.YOLO_TAG }}"

            # DB + ports + optional URL
            export POSTGRES_DB="${{ secrets.POSTGRES_DB || 'predictions' }}"
            export POSTGRES_USER="postgres"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD || 'postgres' }}"
            export YOLO_PORT="8080"
            export OLLAMA_UI_PORT="3000"

            # If Ollama runs on the host, containers should use host.docker.internal
            export OLLAMA_URL="${{ secrets.OLLAMA_URL || 'http://host.docker.internal:11434' }}"

            # sudo drops env by default; preserve what compose needs
            SUDO_ENV="--preserve-env=DOCKERHUB_USERNAME,OLLAMA_UI_IMG_TAG,YOLO_IMG_TAG,POSTGRES_DB,POSTGRES_USER,POSTGRES_PASSWORD,YOLO_PORT,OLLAMA_UI_PORT,OLLAMA_URL"

            # Pull and start (ignore any /home/ubuntu/.env)
            sudo $SUDO_ENV docker compose --env-file /dev/null pull
            sudo $SUDO_ENV docker compose --env-file /dev/null up -d --remove-orphans

            # Quick health check + useful diagnostics in the logs
            for i in {1..30}; do
              if curl -fsS "http://localhost:${OLLAMA_UI_PORT}" >/dev/null; then
                echo "UI is up"
                break
              fi
              echo "Waiting for UI... ($i)"
              sleep 5
            done

            echo "--- docker compose ps ---"
            sudo $SUDO_ENV docker compose ps

            echo "--- last 100 lines of each service ---"
            sudo $SUDO_ENV docker compose logs --tail=100 db || true
            sudo $SUDO_ENV docker compose logs --tail=100 api || true
            sudo $SUDO_ENV docker compose logs --tail=100 ollama-ui || true

            echo "--- resolved compose config (for env substitution sanity) ---"
            sudo $SUDO_ENV docker compose --env-file /dev/null config


      - name: Checkout tests (OllamaUITesting)
        uses: actions/checkout@v4
        with:
          repository: YOUR_GITHUB_ORG_OR_USER/OllamaUITesting
          path: tests
          token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        working-directory: tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Create Allure environment metadata
        working-directory: tests
        run: |
          mkdir -p allure-results
          cat > allure-results/environment.properties <<EOF
          OLLAMA_UI_IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          YOLO_IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/yolo:${{ env.YOLO_TAG }}
          POSTGRES_IMAGE=postgres:15
          BASE_URL=http://${{ secrets.EC2_HOST }}:3000
          EOF

      - name: Run Selenium tests (matrix via loops)
        working-directory: tests
        env:
          BASE_URL: http://${{ secrets.EC2_HOST }}:3000
        run: |
          set -e
          for B in $BROWSERS; do
            for R in $RESOLUTIONS; do
              OUT="allure-results/${B}-${R//\//x}"`
              mkdir -p "$OUT"
              echo "=== Running tests: browser=$B res=$R ==="
              pytest -q \
                --browser "$B" \
                --window-size "$R" \
                --base-url "$BASE_URL" \
                --alluredir="$OUT"
            done
          done

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: tests/allure-results
