name: E2E Deploy & Test (EC2)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ollama
      # Browsers/resolutions you want to test (space-separated lists)
      BROWSERS: "chrome firefox"
      RESOLUTIONS: "1920x1080 1366x768"

    steps:
      - name: Checkout OllamaUI
        uses: actions/checkout@v4

      # Login to Docker Hub with an access token
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Unique tag for the UI image
      - name: Compute image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}-${GITHUB_RUN_ID}" >> $GITHUB_ENV

      # Optional: compute YOLO tag (fallback to 'latest' if secret is empty)
      - name: Compute YOLO tag
        run: |
          if [ -n "${{ secrets.YOLO_IMAGE_TAG }}" ]; then
            echo "YOLO_TAG=${{ secrets.YOLO_IMAGE_TAG }}" >> $GITHUB_ENV
          else
            echo "YOLO_TAG=latest" >> $GITHUB_ENV
          fi

      # Build & push the UI image
      - name: Build & push OllamaUI image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Copy Docker Compose file to EC2
      - name: Copy docker-compose.yaml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/ubuntu/"

      # Deploy on EC2 (no .env file—exports only; force Compose to ignore any local .env)
      - name: Deploy stack on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # Ensure docker compose plugin exists
            if ! docker compose version >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y docker-compose-plugin
            fi

            cd /home/ubuntu

            # Login to Docker Hub on the instance
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # --- Export env vars for Compose substitution (NO .env file) ---
            export DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_NAMESPACE }}"
            export OLLAMA_UI_IMG="${{ env.IMAGE_TAG }}"
            export YOLO_IMAGE="${{ secrets.DOCKERHUB_NAMESPACE }}/yolo:${{ env.YOLO_TAG }}"
            export POSTGRES_DB="predictions"
            export POSTGRES_USER="postgres"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export YOLO_PORT="8080"
            export OLLAMA_UI_PORT="3000"
            # Optional: if your app reads this
            export OLLAMA_URL="${{ secrets.OLLAMA_URL }}"

            # Bring up / refresh the stack (force Compose to ignore any /home/ubuntu/.env)
            docker compose --env-file /dev/null down || true
            docker compose --env-file /dev/null pull || true
            docker compose --env-file /dev/null up -d --remove-orphans

            # Wait for UI to respond
            for i in {1..30}; do
              if curl -fsS "http://localhost:${OLLAMA_UI_PORT}" >/dev/null; then
                echo "UI is up"; break
              fi
              echo "Waiting for UI... ($i)"
              sleep 5
            done

      # ---------- Selenium E2E tests against the EC2 public URL ----------

      - name: Checkout tests (OllamaUITesting)
        uses: actions/checkout@v4
        with:
          repository: YOUR_GITHUB_ORG_OR_USER/OllamaUITesting
          path: tests
          token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        working-directory: tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install browsers for the runner
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set up Firefox
        uses: browser-actions/setup-firefox@v1

      # Allure environment metadata
      - name: Create Allure environment metadata
        working-directory: tests
        run: |
          mkdir -p allure-results
          cat > allure-results/environment.properties <<EOF
          OLLAMA_UI_IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          YOLO_IMAGE=${{ secrets.DOCKERHUB_NAMESPACE }}/yolo:${{ env.YOLO_TAG }}
          POSTGRES_IMAGE=postgres:15
          BASE_URL=http://${{ secrets.EC2_HOST }}:3000
          EOF

      - name: Run Selenium tests (matrix via loops)
        working-directory: tests
        env:
          BASE_URL: http://${{ secrets.EC2_HOST }}:3000
        run: |
          set -e
          for B in $BROWSERS; do
            for R in $RESOLUTIONS; do
              OUT="allure-results/${B}-${R//\//x}"
              mkdir -p "$OUT"
              echo "=== Running tests: browser=$B res=$R ==="
              pytest -q \
                --browser "$B" \
                --window-size "$R" \
                --base-url "$BASE_URL" \
                --alluredir="$OUT"
            done
          done

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: tests/allure-results
