name: Advanced Selenium UI Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  selenium-matrix-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        resolution:
          - { name: 'desktop-full', width: 1920, height: 1080 }
          - { name: 'laptop',       width: 1366, height: 768 }
          - { name: 'mobile',       width: 375,  height: 667 }

    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Checkout UI tests repo
        uses: actions/checkout@v4
        with:
          repository: Hadi-Serhan/OllamaUITesting
          token: ${{ secrets.UI_TESTING_GITHUB_TOKEN }}
          path: ui-tests

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (from tests repo)
        working-directory: ui-tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1

      - name: Set up Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1

      - name: Run Selenium tests
        working-directory: ui-tests
        env:
          HEADLESS: 'true'
          BROWSER: ${{ matrix.browser }}
          SCREEN_WIDTH: ${{ matrix.resolution.width }}
          SCREEN_HEIGHT: ${{ matrix.resolution.height }}
          APP_URL: ${{ secrets.APP_URL }}  
        run: |
          pytest tests/ -v --tb=short
